### ISSUE TITLE
highcharts

### ISSUE THREAD

**Issue by pokotyamu** [feedforce/morning-meeting-chart#1]
[PerfectlyNormal/highcharts-rails: Simple gem to include Highcharts in a Rails 3.1 (or above) app](https://github.com/PerfectlyNormal/highcharts-rails)

**Comment by pokotyamu** [comment]
![dsc_0061](https://cloud.githubusercontent.com/assets/3479317/16559161/e74a6d0c-4225-11e6-956f-a818b12dc7a0.JPG)

**Comment by pokotyamu** [comment]
グラフのセッティングはこんな感じになると思われ
[Combination Chart · michelson/lazy_high_charts Wiki](https://github.com/michelson/lazy_high_charts/wiki/Combination-Chart)

**Comment by hanocha** [comment]
@pokotyamu 

issueに残ってるのもなんか違う気がするので、
手が空いた時にでもwikiかなんかに情報移すとかして欲しい感ある。

**Comment by pokotyamu** [comment]
うっす。
