### ISSUE TITLE
今後の開発の流れ

### ISSUE THREAD

**Issue by otofu-square** [feedforce/morning-meeting-chart#46]
今後の開発で何をどの順で作っていくかみんなで話し合ったことのメモ。
### 優先度高
- グラフサイズをもう少し大きくする ( @hanocha  ) #58 
- チームの順番をソートする機能 ( @hanocha  ) #53 
- 棒グラフを一番下に持ってきて目標の線が隠れないようにする () #57 
  - 棒グラフを透明化してどうにかならないか検討してみる
### 優先度中
- テストを書く
- Qiita投稿ボタン #8 ( @otofu-square )
### 優先度低
- 週の開始日/終了日をいちいち入力するのをやめたい #38

**Comment by hanocha** [comment]
> チームの順番をソートする機能

#44 と結構密接に関わってるので、こっちで巻き取っちゃっていいかな？

**Comment by hanocha** [comment]
と、グラフサイズ拡大とプレビュー全画面って同じ目的だと思ってるんだけど…別件？

**Comment by pokotyamu** [comment]
Q 毎のグラフも出ると嬉しいのかなと思った(キックオフの時に使える的な意味で

**Comment by pokotyamu** [comment]
> 棒グラフを一番下に持ってきて目標の線が隠れないようにする

これは調査の結果、 js 自体が対応してないから、無理っぽい

**Comment by otofu-square** [comment]
Issue 整理のため一旦クローズ
