### ISSUE TITLE
全体で共有したいことを登録できる機能がほしい

### ISSUE THREAD

**Issue by hanocha** [feedforce/morning-meeting-chart#48]
全体共有事項がある時に
事前にそれを登録しておけるような何かがあるといいよね、という話をかのえさんとした。

**Comment by kano-e** [comment]
今はいちいち Slack 上で「この URL を表示して欲しい」とか「次の司会誰でしたっけ」とかやりとりしてて煩雑そうに見えました。
この機能があれば、共有事項がある人はあらかじめ自分で内容を入力しておけば良いだけだし、司会の人も登録されたものを表示するだけで良いので便利になると思いました (感想)

**Comment by pokotyamu** [comment]
どんな実装になるんだろうか.
新しく model 作らなきゃかな？

**Comment by pokotyamu** [comment]
Topic に URL っぽいものが入ってたら、そっからリンクできるようにもしたくなる気がしている。
今は無理そうだし

**Comment by pokotyamu** [comment]
> 新しく model 作らなきゃかな？

専用の model を作るということで、 @hanocha と話した

**Comment by hanocha** [comment]
Information モデルかなぁ
Progress-Information 、 1対多。

既存のTeam、Goal、Progressなどとは完全に切り離されたモデルになる。
が、プレビュー時に表示するInformationを選択するロジックをどうするか…
（プレビュー時から数えて1週間以内に登録されたInformationを表示対象にする、でいいのかな）

改修規模は大きめだけど他との衝突はそんなになさそう。

**Comment by pokotyamu** [comment]
@hanocha 特に、Progress と持たせる必要性を感じないんだけど...
普通に順番の最後のチームの後にリンクに飛ぶ感じにしたらいいんじゃない？

**Comment by pokotyamu** [comment]
登録日は直近１週間以内にするか、発表日を選ぶ感じだろうね

**Comment by pokotyamu** [comment]
もはや一覧ページ的な感じで出しちゃっても良いかもしれない

**Comment by hanocha** [comment]
あー、なんか酔った頭で色々考えながら書いたから矛盾が…
Progressと対応させる必要はないっす。たぶん消し忘れ。すんません。

発表日を選んでもらうのが若干面倒そう（そういう機能があるのはいいとして）かなと思ったので、
たぶん1週間以内に登録されたものを使う、という感じにすると思う

**Comment by hanocha** [comment]
#67

**Comment by pokotyamu** [comment]
マージされたから、閉じる
